_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 12
                - 45
                - 55
                - 77
            "3":
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.11
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
actor_graph_aggr:
    value: node
algorithm_name:
    value: rmappo
auto_mini_batch_size:
    value: true
checkpoint_interval:
    value: 50
clip_param:
    value: 0.2
collaborative:
    value: false
collision_rew:
    value: 5
critic_graph_aggr:
    value: global
critic_lr:
    value: 0.0007
cuda:
    value: true
cuda_deterministic:
    value: true
data_chunk_length:
    value: 10
discrete_action:
    value: true
dynamics_type:
    value: airtaxi
embed_add_self_loop:
    value: false
embed_hidden_size:
    value: 16
embed_layer_N:
    value: 1
embed_use_ReLU:
    value: true
embedding_size:
    value: 2
entropy_coef:
    value: 0.01
env_name:
    value: GraphMPE
episode_length:
    value: 350
eval_episodes:
    value: 32
eval_interval:
    value: 25
experiment_name:
    value: hesse_250130_204850_agent4_landmark2_eplength350_world6
fair_rew:
    value: 1
fair_wt:
    value: 1
gae_lambda:
    value: 0.95
gain:
    value: 0.01
gamma:
    value: 0.99
global_aggr_type:
    value: mean
gnn_concat_heads:
    value: false
gnn_hidden_size:
    value: 16
gnn_layer_N:
    value: 2
gnn_num_heads:
    value: 3
gnn_use_ReLU:
    value: true
goal_rew:
    value: 5
graph_feat_type:
    value: relative
hidden_size:
    value: 64
horizon:
    value: 1
huber_delta:
    value: 10
ifi:
    value: 0.1
img_interval:
    value: 2
increase_fairness:
    value: false
layer_N:
    value: 1
log_interval:
    value: 5
lr:
    value: 0.0007
max_batch_size:
    value: 32
max_grad_norm:
    value: 10
min_dist_thresh:
    value: 0.05
model_dir:
    value: trained_models/airtaxi_no_penalty
n_eval_rollout_threads:
    value: 1
n_render_rollout_threads:
    value: 1
n_rollout_threads:
    value: 32
n_training_threads:
    value: 1
num_agents:
    value: 4
num_agents_per_team:
    value: 3
num_embeddings:
    value: 4
num_env_steps:
    value: 10000000
num_internal_step:
    value: 1
num_landmarks:
    value: 2
num_mini_batch:
    value: 10
num_nbd_entities:
    value: 3
num_obstacles:
    value: 0
num_prediction_step_eval:
    value: 1
num_scripted_agents:
    value: 0
num_teams:
    value: 1
num_walls:
    value: 0
obs_type:
    value: global
opti_eps:
    value: 1e-05
ppo_epoch:
    value: 10
project_name:
    value: airtaxi_env_random_safety_1
recurrent_N:
    value: 1
render_episodes:
    value: 5
render_eval:
    value: false
save_gifs:
    value: true
save_interval:
    value: 1
scenario_name:
    value: navigation_graph_safe
seed:
    value: 0
share_policy:
    value: true
soft_filter_type:
    value: none
split_batch:
    value: false
stacked_frames:
    value: 1
target_mini_batch_size:
    value: 4096
use_ReLU:
    value: false
use_cent_obs:
    value: false
use_centralized_V:
    value: true
use_clipped_value_loss:
    value: true
use_comm:
    value: false
use_dones:
    value: false
use_eval:
    value: false
use_feature_normalization:
    value: true
use_gae:
    value: true
use_huber_loss:
    value: true
use_linear_lr_decay:
    value: false
use_masking:
    value: true
use_max_grad_norm:
    value: true
use_naive_recurrent_policy:
    value: false
use_obs_instead_of_state:
    value: false
use_orthogonal:
    value: true
use_policy_active_masks:
    value: true
use_popart:
    value: true
use_proper_time_limits:
    value: false
use_recurrent_policy:
    value: true
use_render:
    value: false
use_safety_filter:
    value: true
use_stacked_frames:
    value: false
use_value_active_masks:
    value: true
use_valuenorm:
    value: false
use_wandb:
    value: true
user_name:
    value: ucb_mit_marl
value_loss_coef:
    value: 1
verbose:
    value: true
weight_decay:
    value: 0
world_size:
    value: 6
zeroshift:
    value: 3
